ktor {
    deployment {
        port = 8080
        port = ${?PORT} # GCP injecte souvent le port via cette variable
    }

    application {
        modules = [ com.example.ApplicationKt.module ]
    }
}

services {
    user {
        # On cherche la variable d'env MS_USER_URL, sinon on utilise localhost
        url = "http://ms-user-default/mobile"
        url = ${?MS_USER_URL}
    }
    cards {
        url = "http://ms-cards-default/mobile"
        url = ${?MS_CARDS_URL}
    }
}